name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.WPENGINE_SSH_PRIVATE_KEY }}  
    - run: ssh-keyscan git.wpengine.com >> ~/.ssh/known_hosts
    - run: docker-compose up -d
    - run: npm ci
      working-directory: test
#     - run: npm test
#       working-directory: test
    - run: git push -f git@git.wpengine.com:staging/stanforddaily2.git main
    - run: git pull git@git.wpengine.com:production/stanforddaily2.git main
    - run: git push git@git.wpengine.com:production/stanforddaily2.git main
